#server.R
#Capstone project Coursera Data Science
#Mario Reyes

# load the n-gram frequencies (generated by "build-ngram-frequencies.R")
bigram <- readRDS("./data/bigram.RData")
trigram <- readRDS("./data/trigram.RData")
quadgram <- readRDS("./data/quadgram.RData")


# Profanity words file
# List of profanity words taken from https://www.cs.cmu.edu/~biglou/resources/bad-words.txt
profanity_words <-readLines("./data/bad-words.txt", encoding="UTF-8")
profanity_words <- iconv(profanity_words, "latin1", "ASCII", sub = "")

predict_ngrams <- function(text_input, ngrams) {
  
  # For quadgrams and higher
  if (ngrams > 3) {
    text_input3 <- paste(text_input[length(text_input) - 2],
                        text_input[length(text_input) - 1],
                        text_input[length(text_input)])
    data_words <- quadgram %>% filter(variable == text_input3)
    if (nrow(data_words) >= 1) {
      return(data_words$outcome[1:3])
    }
    # Change to trigram
    return(predict_ngrams(text_input, ngrams - 1))
  }
  
  # trigram
  if (ngrams == 3) {
    text_input1 <- paste(text_input[length(text_input)-1], text_input[length(text_input)])
    data_words <- trigram %>% filter(variable == text_input1)
    if (nrow(data_words) >= 1) {
      return(data_words$outcome[1:3])
    }
    # Change to to bigram
    return(predict_ngrams(text_input, ngrams - 1))
  }
  
  # For bigram and lower
  if (ngrams < 3) {
    text_input1 <- text_input[length(text_input)]
    data_words <- bigram %>% filter(variable == text_input1)
    return(data_words$outcome[1:3])
  }
  
  return("Word not in the list")
}

text_cleaned <- function(input) {
  
  if (input == "" | is.na(input)) {
    return("")
  }
  #Convert to lowercase
  input <- tolower(input)
  
  # Remove urls, Twitter handles and similar.
  input <- gsub("^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$","", input)
  input <- gsub("@[^\\s]+", "", input)
  #Convert all question and exclamation marks with dots
  input <- gsub("\\?\\!",".", input)
  #Remove non-printable and non-punctuation characters
  input <- gsub("[^[:print:][:punct:]]","", input)
  #Remove all non-alphabetical characters, but keeping apostrophes and dots
  input <- gsub("[^a-zA-Z' .\r\n]","", input)
  input <- gsub("(\\s+')|('\\s+)","", input)
  # remove profane words
  input <- removeWords(input, profanity_words)
  # Remove whitespace
  input <- gsub("^\\s+|\\s+$", "", input)
  input <- stripWhitespace(input)
  #Remove numbers
  input <- gsub("[0-9](?:st|nd|rd|th)", "", input)

  if (input == "" | is.na(input)) {
    return("")
  }
  
  input <- unlist(strsplit(input, " "))
  
  return(input)
  
}

word_predict <- function(input) {
  
  input <- text_cleaned(input)
  
  if (input[1] == "") {
    output <- "A prediction it's not possible"
  } else if (length(input) == 1) {
    output <- predict_ngrams(input, ngrams = 2)[1]
  } else if (length(input) == 2) {
    output <- predict_ngrams(input, ngrams = 3)[1]
  } else if (length(input) > 2) {
    output <- predict_ngrams(input, ngrams = 4)[1]
  }
  
}

shinyServer(function(input, output) {
  
  output$text_user <- renderText({input$text_input});
  output$text_user2 <- renderText({word_predict(input$text_input)});
  
})
